//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaliteKontrolOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class numuneBilgileri
    {
        public int urun_Id { get; set; }
        public Nullable<System.DateTime> urun_Tarihi { get; set; }
        public string urun_Kodu { get; set; }
        public string urun_MPS { get; set; }
        public string urun_Adi { get; set; }
        public string urun_Firmasi { get; set; }
        public string urun_OnayDurumu { get; set; }
        public string urun_OnaylayanKisi { get; set; }
        public string urun_Aciklama { get; set; }
    }
}
